---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: createreadpods
rules:
- apiGroups: ["*"]
  resources: ["deployments", "configmaps","pods", "secrets","services","namespaces"]
  verbs: ["get","list","watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: createreadpodsbinding
subjects:
- kind: User
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: createreadpods
  apiGroup: rbac.authorization.k8s.io
